### ISSUE TITLE
关于Linux下网易云音乐1.1.0的解决方案

### ISSUE THREAD

**Issue by zqzhang1996** [UbuntuBar/userguide#5]
常用软件推荐.md
测试环境Ubuntu17.10, 网易云音乐1.1.0
将以下两个目录权限设为777即可正常运行
~/.cache/netease-cloud-music
~/.config/netease-cloud-music

详细过程见csdn博客：https://blog.csdn.net/pr0phet_chn/article/details/80023198
可能需要更多Linux发行版下的测试
不怎么用贴吧，有必要的话请直接转发到贴吧

**Comment by ghost** [comment]
好的。。。谢谢

**Comment by zqzhang1996** [comment]
关于wine - qq的指路帮大忙了，刚切换系统正发愁怎么折腾qq呢
